print("hello")
print("classroom")
print("apple tree")
print("white plane")
print("coding")
print("tv shows")
print("music")
print("gold key")
print("neon lights")
print("coffe steam")
print("cat chasing a laser")
print("blue text")
print("doctors appointment")
print("messy room")
print("friend group")
print("iron door")
print("fast car")
print("useful information")
print("healthy food")
print("runaway models")